# Generated by Django 5.0.3 on 2024-07-19 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('target_type', models.CharField(max_length=255)),
                ('target_selection', models.CharField(max_length=255)),
                ('allocation_method', models.CharField(max_length=255)),
                ('value_type', models.CharField(max_length=255)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('customer_segment_prerequisite', models.CharField(blank=True, max_length=255, null=True)),
                ('prerequisite_quantity_range', models.PositiveIntegerField(blank=True, null=True)),
                ('prerequisite_shipping_price_range', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prerequisite_subtotal_range', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prerequisite_to_entitlement_quantity_ratio', models.PositiveIntegerField(blank=True, null=True)),
                ('prerequisite_to_entitlement_purchase', models.PositiveIntegerField(blank=True, null=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('code', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('usage_count', models.IntegerField()),
                ('errors', models.TextField()),
                ('price_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discount.pricerule')),
            ],
        ),
    ]
