# Generated by Django 5.0.3 on 2024-07-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metafield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('key', models.CharField(max_length=64)),
                ('namespace', models.CharField(max_length=255)),
                ('owner_id', models.IntegerField()),
                ('owner_resource', models.CharField(max_length=250)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.TextField()),
                ('type', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('namespace', 'key', 'owner_id', 'owner_resource')},
            },
        ),
    ]
